-- CreateTable
CREATE TABLE `account` (
    `ID_ACCOUNT` INTEGER NOT NULL AUTO_INCREMENT,
    `AMOUNT_ACCOUNT` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATE_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID_ACCOUNT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
